"""GitHub API response payloads for testing."""

from typing import Any


def workflow_run(
    *,
    run_id: int = 19685029666,
    name: str = "Test Workflow",
    display_title: str = "Test Workflow Run",
    status: str = "completed",
    conclusion: str | None = "success",
    html_url: str = "https://github.com/test-owner/test-repo/actions/runs/19685029666",
    created_at: str = "2099-01-01T12:00:00Z",
    updated_at: str = "2099-01-01T12:01:00Z",
) -> dict[str, Any]:
    """Create a workflow run payload for testing.

    Only override parameters that are relevant to the test being written.
    """
    return {
        "id": run_id,
        "name": name,
        "node_id": "WFR_kwLOIGkAUs8AAAAElVG3Ig",
        "head_branch": "main",
        "head_sha": "0dfea5b0df8e2385f94aedb45775ca6c321fd5c7",
        "path": ".github/workflows/test.yml",
        "display_title": display_title,
        "run_number": 278,
        "event": "workflow_dispatch",
        "status": status,
        "conclusion": conclusion,
        "workflow_id": 36849857,
        "check_suite_id": 50784706847,
        "check_suite_node_id": "CS_kwDOIGkAUs8AAAAL0wEhHw",
        "url": f"https://api.github.com/repos/test-owner/test-repo/actions/runs/{run_id}",
        "html_url": html_url,
        "pull_requests": [],
        "created_at": created_at,
        "updated_at": updated_at,
        "actor": {
            "login": "test-user",
            "id": 130390083,
            "node_id": "BOT_kgDOB8WYQw",
            "avatar_url": "https://avatars.githubusercontent.com/u/77755945?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/test-user",
            "html_url": "https://github.com/test-user",
            "followers_url": "https://api.github.com/users/test-user/followers",
            "following_url": "https://api.github.com/users/test-user/following{/other_user}",
            "gists_url": "https://api.github.com/users/test-user/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/test-user/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/test-user/subscriptions",
            "organizations_url": "https://api.github.com/users/test-user/orgs",
            "repos_url": "https://api.github.com/users/test-user/repos",
            "events_url": "https://api.github.com/users/test-user/events{/privacy}",
            "received_events_url": "https://api.github.com/users/test-user/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": False,
        },
        "run_attempt": 1,
        "referenced_workflows": [],
        "run_started_at": created_at,
        "triggering_actor": {
            "login": "test-user",
            "id": 130390083,
            "node_id": "BOT_kgDOB8WYQw",
            "avatar_url": "https://avatars.githubusercontent.com/u/77755945?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/test-user",
            "html_url": "https://github.com/test-user",
            "followers_url": "https://api.github.com/users/test-user/followers",
            "following_url": "https://api.github.com/users/test-user/following{/other_user}",
            "gists_url": "https://api.github.com/users/test-user/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/test-user/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/test-user/subscriptions",
            "organizations_url": "https://api.github.com/users/test-user/orgs",
            "repos_url": "https://api.github.com/users/test-user/repos",
            "events_url": "https://api.github.com/users/test-user/events{/privacy}",
            "received_events_url": "https://api.github.com/users/test-user/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": False,
        },
        "jobs_url": f"https://api.github.com/repos/test-owner/test-repo/actions/runs/{run_id}/jobs",
        "logs_url": f"https://api.github.com/repos/test-owner/test-repo/actions/runs/{run_id}/logs",
        "check_suite_url": "https://api.github.com/repos/test-owner/test-repo/check-suites/50784706847",
        "artifacts_url": f"https://api.github.com/repos/test-owner/test-repo/actions/runs/{run_id}/artifacts",
        "cancel_url": f"https://api.github.com/repos/test-owner/test-repo/actions/runs/{run_id}/cancel",
        "rerun_url": f"https://api.github.com/repos/test-owner/test-repo/actions/runs/{run_id}/rerun",
        "previous_attempt_url": None,
        "workflow_url": "https://api.github.com/repos/test-owner/test-repo/actions/workflows/36849857",
        "head_commit": {
            "id": "0dfea5b0df8e2385f94aedb45775ca6c321fd5c7",
            "tree_id": "b2a84b4e1e9adab7c6ba6a053338feb67a1d80c6",
            "message": "Test commit",
            "timestamp": "2025-06-07T18:56:22Z",
            "author": {"name": "Test User", "email": "test@example.com"},
            "committer": {"name": "Test User", "email": "test@example.com"},
        },
        "repository": {
            "id": 543752274,
            "node_id": "R_kgDOIGkAUg",
            "name": "test-repo",
            "full_name": "test-owner/test-repo",
            "private": False,
            "owner": {
                "login": "test-owner",
                "id": 95301622,
                "node_id": "O_kgDOBa4v9g",
                "avatar_url": "https://avatars.githubusercontent.com/u/95301622?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/test-owner",
                "html_url": "https://github.com/test-owner",
                "followers_url": "https://api.github.com/users/test-owner/followers",
                "following_url": "https://api.github.com/users/test-owner/following{/other_user}",
                "gists_url": "https://api.github.com/users/test-owner/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/test-owner/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/test-owner/subscriptions",
                "organizations_url": "https://api.github.com/users/test-owner/orgs",
                "repos_url": "https://api.github.com/users/test-owner/repos",
                "events_url": "https://api.github.com/users/test-owner/events{/privacy}",
                "received_events_url": "https://api.github.com/users/test-owner/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": False,
            },
            "html_url": "https://github.com/test-owner/test-repo",
            "description": None,
            "fork": False,
            "url": "https://api.github.com/repos/test-owner/test-repo",
            "forks_url": "https://api.github.com/repos/test-owner/test-repo/forks",
            "keys_url": "https://api.github.com/repos/test-owner/test-repo/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/test-owner/test-repo/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/test-owner/test-repo/teams",
            "hooks_url": "https://api.github.com/repos/test-owner/test-repo/hooks",
            "issue_events_url": "https://api.github.com/repos/test-owner/test-repo/issues/events{/number}",
            "events_url": "https://api.github.com/repos/test-owner/test-repo/events",
            "assignees_url": "https://api.github.com/repos/test-owner/test-repo/assignees{/user}",
            "branches_url": "https://api.github.com/repos/test-owner/test-repo/branches{/branch}",
            "tags_url": "https://api.github.com/repos/test-owner/test-repo/tags",
            "blobs_url": "https://api.github.com/repos/test-owner/test-repo/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/test-owner/test-repo/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/test-owner/test-repo/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/test-owner/test-repo/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/test-owner/test-repo/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/test-owner/test-repo/languages",
            "stargazers_url": "https://api.github.com/repos/test-owner/test-repo/stargazers",
            "contributors_url": "https://api.github.com/repos/test-owner/test-repo/contributors",
            "subscribers_url": "https://api.github.com/repos/test-owner/test-repo/subscribers",
            "subscription_url": "https://api.github.com/repos/test-owner/test-repo/subscription",
            "commits_url": "https://api.github.com/repos/test-owner/test-repo/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/test-owner/test-repo/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/test-owner/test-repo/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/test-owner/test-repo/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/test-owner/test-repo/contents/{+path}",
            "compare_url": "https://api.github.com/repos/test-owner/test-repo/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/test-owner/test-repo/merges",
            "archive_url": "https://api.github.com/repos/test-owner/test-repo/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/test-owner/test-repo/downloads",
            "issues_url": "https://api.github.com/repos/test-owner/test-repo/issues{/number}",
            "pulls_url": "https://api.github.com/repos/test-owner/test-repo/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/test-owner/test-repo/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/test-owner/test-repo/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/test-owner/test-repo/labels{/name}",
            "releases_url": "https://api.github.com/repos/test-owner/test-repo/releases{/id}",
            "deployments_url": "https://api.github.com/repos/test-owner/test-repo/deployments",
        },
        "head_repository": {
            "id": 543752274,
            "node_id": "R_kgDOIGkAUg",
            "name": "test-repo",
            "full_name": "test-owner/test-repo",
            "private": False,
            "owner": {
                "login": "test-owner",
                "id": 95301622,
                "node_id": "O_kgDOBa4v9g",
                "avatar_url": "https://avatars.githubusercontent.com/u/95301622?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/test-owner",
                "html_url": "https://github.com/test-owner",
                "followers_url": "https://api.github.com/users/test-owner/followers",
                "following_url": "https://api.github.com/users/test-owner/following{/other_user}",
                "gists_url": "https://api.github.com/users/test-owner/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/test-owner/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/test-owner/subscriptions",
                "organizations_url": "https://api.github.com/users/test-owner/orgs",
                "repos_url": "https://api.github.com/users/test-owner/repos",
                "events_url": "https://api.github.com/users/test-owner/events{/privacy}",
                "received_events_url": "https://api.github.com/users/test-owner/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": False,
            },
            "html_url": "https://github.com/test-owner/test-repo",
            "description": None,
            "fork": False,
            "url": "https://api.github.com/repos/test-owner/test-repo",
            "forks_url": "https://api.github.com/repos/test-owner/test-repo/forks",
            "keys_url": "https://api.github.com/repos/test-owner/test-repo/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/test-owner/test-repo/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/test-owner/test-repo/teams",
            "hooks_url": "https://api.github.com/repos/test-owner/test-repo/hooks",
            "issue_events_url": "https://api.github.com/repos/test-owner/test-repo/issues/events{/number}",
            "events_url": "https://api.github.com/repos/test-owner/test-repo/events",
            "assignees_url": "https://api.github.com/repos/test-owner/test-repo/assignees{/user}",
            "branches_url": "https://api.github.com/repos/test-owner/test-repo/branches{/branch}",
            "tags_url": "https://api.github.com/repos/test-owner/test-repo/tags",
            "blobs_url": "https://api.github.com/repos/test-owner/test-repo/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/test-owner/test-repo/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/test-owner/test-repo/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/test-owner/test-repo/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/test-owner/test-repo/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/test-owner/test-repo/languages",
            "stargazers_url": "https://api.github.com/repos/test-owner/test-repo/stargazers",
            "contributors_url": "https://api.github.com/repos/test-owner/test-repo/contributors",
            "subscribers_url": "https://api.github.com/repos/test-owner/test-repo/subscribers",
            "subscription_url": "https://api.github.com/repos/test-owner/test-repo/subscription",
            "commits_url": "https://api.github.com/repos/test-owner/test-repo/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/test-owner/test-repo/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/test-owner/test-repo/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/test-owner/test-repo/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/test-owner/test-repo/contents/{+path}",
            "compare_url": "https://api.github.com/repos/test-owner/test-repo/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/test-owner/test-repo/merges",
            "archive_url": "https://api.github.com/repos/test-owner/test-repo/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/test-owner/test-repo/downloads",
            "issues_url": "https://api.github.com/repos/test-owner/test-repo/issues{/number}",
            "pulls_url": "https://api.github.com/repos/test-owner/test-repo/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/test-owner/test-repo/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/test-owner/test-repo/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/test-owner/test-repo/labels{/name}",
            "releases_url": "https://api.github.com/repos/test-owner/test-repo/releases{/id}",
            "deployments_url": "https://api.github.com/repos/test-owner/test-repo/deployments",
        },
    }


def workflow_runs_response(
    workflow_runs: list[dict[str, Any]] | None = None,
    total_count: int | None = None,
) -> dict[str, Any]:
    """Create a workflow runs response payload for testing."""
    runs = workflow_runs if workflow_runs is not None else []
    return {
        "total_count": total_count if total_count is not None else len(runs),
        "workflow_runs": runs,
    }
